# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(default='http://localhost/downloads/baxster_admin_panel.zip', max_length=400),
        ),
    ]
