# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(default='http://localhost/images/gridallbum3.png', max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(default='http://localhost/downloads/movie1.zip', max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Planet of the Apes', max_length=200),
        ),
    ]
