# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20160822_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='LOREM IPSUM', max_length=400),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default='2016-03-23', max_length=400),
        ),
    ]
