# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20160826_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.CharField(default='5.0', max_length=400),
        ),
    ]
