# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(default='http://localhost/images/gridallbum3.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default='LOREM IPSUM'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default='2016-03-23', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.CharField(default='5.0', max_length=100),
        ),
    ]
