# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20160826_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(default='http://localhost/images/gridallbum3.png', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(default='http://localhost/downloads/movie1.zip', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Planet of the Apes', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default='2016-03-23', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.CharField(default='5.0', max_length=100, null=True),
        ),
    ]
