# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20160826_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='overview',
            new_name='description',
        ),
    ]
