# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20160826_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_link',
            field=models.CharField(default='http://dl.fardadownload.ir/Film/2016/Suicide.Squad.2016.%20English.CAM.FardaDownload.mp4', max_length=400, null=True),
        ),
    ]
