# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_movie_watch_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='link',
            new_name='download_link',
        ),
    ]
