# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20160827_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='year',
        ),
    ]
