# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20160827_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
