# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20160828_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(default='http://image.tmdb.org/t/p/w300/zrAO2OOa6s6dQMQ7zsUbDyIBrAP.jpg', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
