# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_genre_moviegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='download_link',
            field=models.CharField(default='http://www.movieclick.xyz/movie_not_found', max_length=400, null=True),
        ),
    ]
