# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_auto_20160829_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watch_link',
            field=models.CharField(default='http://www.movieclick.xyz/movie_not_found', max_length=400, null=True),
        ),
    ]
