# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20160831_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieNotFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
