# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_movienotfound'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieNotFound',
            new_name='NotFoundMovie',
        ),
    ]
