# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_notfoundmovie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(default='http://www.movieclick.xyz/movie_not_found', max_length=400, null=True),
        ),
    ]
