# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_auto_20160902_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='userText',
            new_name='feedback',
        ),
    ]
